### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by franciscoabenza** [denonrailz/obsidian-autogen#1]
Hey man it is so sad that we didn't get to know each other before U.u (I had this idea for a very long time (I even have some code) but you took it to the next level. Congrats :)

I would genuinely enjoy having a chat with you as I have many inputs that could help this product being super valuable for a lot of people: [schedule a meeting 📆](https://cal.com/franabenza)

Reasonable integration: [canvas+autogen](https://github.com/DeabLabs/cannoli)

**Comment by denonrailz** [comment]
awesome, @franciscoabenza send you invite
